version: '3'
services:
  app:
    container_name: limarka-render-app
    image: reinanhs/php81-composer-npm
    command: bash -c "composer install && vendor/bin/jigsaw serve --port=8080"
    working_dir: /var/www/html
    environment:
      APP_BASE_URL: '/'
      APP_LANGUAGE: 'pt_BR'
      GITHUB_REPOSITORY_OWNER: 'reinanhs'
      GITHUB_REPOSITORY: 'reinanhs/limarka-render-html'
    volumes:
      - '.:/var/www/html'
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./build_local:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/