version: '3'
services:
  app:
    container_name: limarka-render-app
    image: reinanhs/php81-composer-npm
    tty: true
    command: "/bin/bash"
    working_dir: /var/www/html
    environment:
      APP_BASE_URL: '/'
      APP_LANGUAGE: 'pt_BR'
      GITHUB_REPOSITORY_OWNER: 'reinanhs'
      GITHUB_REPOSITORY: 'reinanhs/limarka-render-html'
    volumes:
      - '.:/var/www/html'
  app-test:
    container_name: limarka-render-test
    image: reinanhs/limarka-render-html:0.0.2
    tty: true
    command: "/bin/bash"
    environment:
      APP_BASE_URL: '/'
      APP_LANGUAGE: 'pt_BR'
      GITHUB_REPOSITORY_OWNER: 'reinanhs'
      GITHUB_REPOSITORY: 'reinanhs/limarka-render-html'
    volumes:
      - './build_local:/var/www/html/build_local'
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./build_local:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/